# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome as qta

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 80)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileNameLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.fileNameLabel.setFont(font)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.horizontalLayout_2.addWidget(self.fileNameLabel)
        self.openDirPushButton = QtWidgets.QPushButton(self.widget)
        self.openDirPushButton.setObjectName("openDirPushButton")
        self.openDirPushButton.setMaximumSize(40, 20)
        self.openDirPushButton.setIcon(qta.icon("fa5.folder-open", color="gray"))
        self.openDirPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openDirPushButton.setToolTip("在文件夹打开")
        self.horizontalLayout_2.addWidget(self.openDirPushButton)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setMaximumSize(40, 20)
        self.pushButton.setIcon(qta.icon("fa5.stop-circle", color="gray"))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setToolTip("暂停")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 381, 47))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setMaximumSize(374, 15)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadSizeLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.downloadSizeLabel.setFont(font)
        self.downloadSizeLabel.setObjectName("downloadSizeLabel")
        self.downloadSizeLabel.setAlignment(QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.downloadSizeLabel)
        self.remainTimeLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.remainTimeLabel.setFont(font)
        self.remainTimeLabel.setObjectName("remainTimeLabel")
        self.remainTimeLabel.setAlignment(QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.remainTimeLabel)
        self.speedLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.speedLabel.setFont(font)
        self.speedLabel.setObjectName("speedLabel")
        self.speedLabel.setAlignment(QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.speedLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fileNameLabel.setText(_translate("Form", "文件名"))
        self.pushButton.setText(_translate("Form", ""))
        self.downloadSizeLabel.setText(_translate("Form", "11.0KB/25.64MB"))
        self.remainTimeLabel.setText(_translate("Form", "00:00:45"))
        self.speedLabel.setText(_translate("Form", "124.66KB/S"))