# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome as qta

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.smallerPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.smallerPushButton.setMaximumSize(QtCore.QSize(15, 15))
        self.smallerPushButton.setText("")
        self.smallerPushButton.setObjectName("smallerPushButton")
        self.smallerPushButton.setGeometry(QtCore.QRect(37, 5, 20, 20))
        self.closePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.closePushButton.setMaximumSize(QtCore.QSize(15, 15))
        self.closePushButton.setText("")
        self.closePushButton.setObjectName("closePushButton")
        self.closePushButton.setGeometry(QtCore.QRect(10, 5, 20, 20))
        self.fileNumlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.fileNumlabel.setFont(font)
        self.fileNumlabel.setText("")
        self.fileNumlabel.setObjectName("fileNumlabel")
        self.gridLayout.addWidget(self.fileNumlabel, 2, 1, 1, 1)
        self.totalFileLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.totalFileLabel.setFont(font)
        self.totalFileLabel.setObjectName("totalFileLabel")
        self.gridLayout.addWidget(self.totalFileLabel, 2, 0, 1, 1)
        self.totalSizelabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.totalSizelabel.setFont(font)
        self.totalSizelabel.setObjectName("totalSizelabel")
        self.gridLayout.addWidget(self.totalSizelabel, 2, 2, 1, 1)
        self.fileSizeLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.fileSizeLabel.setFont(font)
        self.fileSizeLabel.setText("")
        self.fileSizeLabel.setObjectName("fileSizeLabel")
        self.gridLayout.addWidget(self.fileSizeLabel, 2, 3, 1, 1)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 4)
        self.filePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.filePushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.filePushButton.setText("")
        self.filePushButton.setObjectName("filePushButton")
        self.filePushButton.setIcon(qta.icon("fa5s.folder-plus", color = "yellow"))
        self.gridLayout.addWidget(self.filePushButton, 3, 3, 1, 1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setFont(font)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.gridLayout.addWidget(self.fileLineEdit, 3, 0, 1, 3)
        self.diskSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.diskSizeLabel.setFont(font)
        self.diskSizeLabel.setObjectName("diskSizeLabel")
        self.gridLayout.addWidget(self.diskSizeLabel, 3, 2, 1, 1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.downloadPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadPushButton.setObjectName("downloadPushButton")
        self.downloadPushButton.setFont(font)
        self.block = QtWidgets.QLabel(self.centralwidget)
        self.gridLayout.addWidget(self.block, 4, 0, 1, 4)
        self.gridLayout.addWidget(self.downloadPushButton, 5, 0, 1, 4)
        self.gridLayout.setGeometry(QtCore.QRect(10, 25, 296, 318))
        self.downloadListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.downloadListWidget.setObjectName("downloadListWidget")
        self.downloadListWidget.setGeometry(QtCore.QRect(327, 25, 400, 308))
        MainWindow.setCentralWidget(self.centralwidget)

        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.totalFileLabel.setText(_translate("MainWindow", "总文件数："))
        self.totalSizelabel.setText(_translate("MainWindow", "总大小："))
        self.downloadPushButton.setText(_translate("MainWindow", "立即下载"))